# Generated by Django 4.1.2 on 2024-06-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantitaricaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='insumos',
            options={'verbose_name_plural': 'Insumos'},
        ),
        migrations.AlterModelOptions(
            name='maceteros',
            options={'verbose_name_plural': 'Maceteros'},
        ),
        migrations.AlterModelOptions(
            name='plantas',
            options={'verbose_name_plural': 'Plantas'},
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='maceteros',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plantas',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
