# Generated by Django 5.0.6 on 2024-06-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantitaricaApp', '0002_encarro_alter_insumos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='Insumos'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maceteros',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maceteros',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='Maceteros'),
        ),
        migrations.AlterField(
            model_name='maceteros',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plantas',
            name='foto',
            field=models.ImageField(default='default.jpg', upload_to='Productos'),
        ),
        migrations.AlterField(
            model_name='plantas',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
