# Generated by Django 5.0.6 on 2024-06-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantitaricaApp', '0003_alter_insumos_descripcion_alter_insumos_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Insumos/', verbose_name='Foto del Insumo'),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='maceteros',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='maceteros',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Maceteros/', verbose_name='Foto del Macetero'),
        ),
        migrations.AlterField(
            model_name='maceteros',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plantas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Plantas/', verbose_name='Foto de la planta'),
        ),
        migrations.AlterField(
            model_name='plantas',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
