# Generated by Django 4.1.2 on 2024-07-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantitaricaApp', '0004_alter_insumos_descripcion_alter_insumos_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encarro',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
